services:
  - type: web
    name: django-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn avatar_api.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: avatar_api.settings
      - key: SECRET_KEY
        value: your-secret-key
      - key: ALLOWED_HOSTS
        value: .onrender.com 